# Generated by Django 4.1.4 on 2022-12-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('birthday_date', models.DateField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('place_employment', models.CharField(blank=True, max_length=1000, null=True)),
                ('gto_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SportObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sport_object',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'team',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypeSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'type_sport',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SportTypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('sport_object', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eventHandler.sportobject')),
                ('type_sport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eventHandler.typesport')),
            ],
            options={
                'db_table': 'sport_type_event',
                'managed': True,
                'unique_together': {('id', 'sport_object', 'type_sport')},
            },
        ),
        migrations.CreateModel(
            name='SportsmanSportTypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type_event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eventHandler.sporttypeevent')),
                ('sportsman', models.ForeignKey(db_column='sportsman', on_delete=django.db.models.deletion.DO_NOTHING, to='eventHandler.authuser')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eventHandler.team')),
            ],
            options={
                'db_table': 'sportsman_sport_type_event',
                'managed': True,
                'unique_together': {('id', 'team', 'sportsman', 'sport_type_event')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, to='eventHandler.authuser')),
                ('settings', models.ForeignKey(db_column='settings', on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_settings', to='eventHandler.sporttypeevent')),
            ],
            options={
                'db_table': 'event',
                'managed': True,
                'unique_together': {('id', 'owner')},
            },
        ),
    ]
