# Generated by Django 4.1.2 on 2022-11-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name')),
                ('date', models.DateField(db_column='date')),
                ('person', models.TextField(db_column='person')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
