# Generated by Django 4.1.2 on 2022-11-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typesport',
            table='type_sport',
        ),
    ]
