# Generated by Django 4.1.2 on 2022-11-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventHandler', '0002_alter_typesport_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSportOnEvent',
            fields=[
                ('sportType', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='eventHandler.typesport')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eventHandler.event')),
            ],
        ),
    ]
