# Generated by Django 4.1.2 on 2022-11-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventHandler', '0003_typesportonevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typesportonevent',
            options={'managed': False},
        ),
    ]
