# Generated by Django 4.1.4 on 2023-01-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventHandler', '0004_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsmansporttypeevent',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
