# Generated by Django 4.1.2 on 2022-11-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventHandler', '0004_alter_typesportonevent_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typesportonevent',
            table='typesportonevent',
        ),
    ]
